name: hours_guru

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0
    ports:
      - "5000:5000" # MLflow UI
    volumes:
      - mlflow_data:/mlflow
    environment:
      MLFLOW_TRACKING_URI: "http://localhost:5000"

volumes:
  db:
  mlflow_data: